version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'while !<dev/tcp/db/5432; do sleep 1; done; npm start'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:991112@postgres:5432/first_build
      NODE_ENV: development
      PORT: 3001
    ports:
      - '8080:3001'

  postgres:
    image: postgres:15
    ports:
      - '35000:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 991112
      POSTGRES_DB: first_build
